eno=int(input('enter employee no:'))
ename=input('enter employee name:')
esal=int(input('enter employee salary:'))
eaddr=input('employee address:')
print('employee no:',eno)
print('employee name:',ename)
print('employee salary:',esal)
print('employee address:',eaddr)